### ISSUE TITLE
Cloud Bigtable emulator for instances

### ISSUE THREAD

**Issue by sduskis** [googleapis/google-cloud-go#1069]
The Cloud Bigtable emulator is great for testing table admin and data operations.  It would be ideal to also support Instance and Cluster admin operations.  To start, support Cluster/Instance/AppProfile CRUD operations.  Those operations should keep an in memory list of the objects.  The emulator's table admin and data operations ought not be affected by this enhancement.

- [ ] Support Instance Admin (issue #1092)
- [ ] Support Cluster Admin (issue #1093)
- [ ] Support AppProfiles (issue #1094)
- [ ] Support IAM Policies (issue #1095)

**Comment by tritone** [comment]
All child issues of this were closed as deprioritized and the issue hasn't been updated in over a year, so I'm going to close this one out. Feel free to open a new issue if anything is still relevant.
